# Generated by Django 5.2.3 on 2025-09-24 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunSQL(
            "ALTER TABLE ProviderBill ADD COLUMN assigned_worker VARCHAR(20) NULL;",
            reverse_sql="ALTER TABLE ProviderBill DROP COLUMN assigned_worker;"
        ),
    ]
